spring:
  application:
    name: usuarios
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5433}/usuarios
    username: usuarios
    password: usuarios123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 8081

security:
  jwt:
    secret: "change-me-secret-with-at-least-32-characters"
    expiration-seconds: 3600
