spring:
  application:
    name: zonas
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5433}/zonas
    username: zonas
    password: zonas123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
